services:
  auth-api:
    container_name: auth-api
    image: auth-api
    build:
      context: ./server/src
      dockerfile: DailyCashFlow.Auth/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=DailyCashFlowDB;User Id=sa;Password=YourStrong@Passw0rd;Encrypt=False;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80

  web-api:
    container_name: web-api
    image: web-api
    build:
      context: ./server/src
      dockerfile: DailyCashFlow.WebApi/Dockerfile
    ports:
      - "5003:80"
    depends_on:
      - sqlserver
      - rabbitmq
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=DailyCashFlowDB;User Id=sa;Password=YourStrong@Passw0rd;Encrypt=False;
      - NServiceBus__RabbitMQ__ConnectionString=host=rabbitmq;username=guest;password=guest
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80

  processor:
    container_name: processor
    image: processor
    build:
      context: ./server/src
      dockerfile: DailyCashFlow.Processor/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=DailyCashFlowDB;User Id=sa;Password=YourStrong@Passw0rd;Encrypt=False;
      - NServiceBus__RabbitMQ__ConnectionString=host=rabbitmq;username=guest;password=guest

  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672" # Porta padrão do RabbitMQ (usada pelo NServiceBus)
      - "15672:15672" # Porta da interface de gerenciamento (acessível via browser)

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  sqlvolume:
  portainer_data:
